### ISSUE TITLE
Multiple reverting

### ISSUE THREAD

**Issue by w3con** [BlockchainLabsNZ/tge-contract-audit#2]
[Line 224](https://github.com/BlockchainLabsNZ/tge-contract-audit/blob/2207b0d258c5dd4b35e3aaeca31077eb709d8d42/contracts/OMITokenLock.sol#L224):
```
    for (uint256 i = _from; i < _to; i = i.add(1)) {
      address _beneficiary = lockIndexes[i];

      //Skip any previously removed locks
      if (_beneficiary == 0x0) {
        continue;
      }

      require(_release(_beneficiary));
    }
```

If `require(_release(_beneficiary))` fails by some reason, all `releaseAll()` function will fail. 
Probably, it could be better to log failed release and continue the loop.

**Comment by mikelduffy** [comment]
In order to log an event and continue the loop, the require statements in StandardToken.sol/transferFrom function would also have to be overwritten. Unless there is another way to accomplish this, I would prefer not to overwrite the basic functions of the ERC20 contracts.

**Comment by w3con** [comment]
ERC20 defines interfaces, not an implementations. 
OpenZeppelin’s approach is good and well tested but is not the standard, but you right,  it is not usually recommended to change such common frameworks due to the possibility to break the logic.

I can see three options: 
1. Accept this multiple-reverting risk (as you did)
2. Change Zeppelin’s function
3. Move `releaseAll()` logic away from Solidity to the web, since the function has `onlyOwner` modifier, means it can not be used by everyone. 

You may consider all of that solutions and choose one which suits you best, which you probably already did. 

Anyway, this issue could bring some annoyance but is not critical concerning its consequences.

**Comment by mikelduffy** [comment]
The third option above makes a lot of sense as it gives us the most control. I've replaced the releaseAll logic.
