### ISSUE TITLE
Zeppelin Solidity framework was renamed

### ISSUE THREAD

**Issue by w3con** [BlockchainLabsNZ/tge-contract-audit#4]
Repository "zeppelin-solidity" was renamed to the "openzeppelin-solidity" in May, 2018.<br>If One uses `yarn` to install dependencies, the changes in the contracts "import" statements are required, since `yarn` distinguish these repos and import paths from the contract won't be found. 

On the contrary, `npm` warn about this situation, but install old "zeppelin-solidity" repository, so no extra actions are required. 

No original OpenZeppelin Solidity framework contracts were changed.

**Comment by mikelduffy** [comment]
I tried removing node_modules and yarn.lock then installing with `npm install`, but I am still getting unresolved imports using `import "openzeppelin-solidity/contracts/ownership/Ownable.sol";`.

**Comment by w3con** [comment]
Try these steps:
1. Remove `build` folder
2. run ganache/testrpc
3. `truffle compile`
4. `truffle migrate`
5. `npm test`

**Comment by mikelduffy** [comment]
Fixed. I had to remove `zeppelin-solidity` from package.json and then install `openzeppelin-solidity`, and then the above steps work.

**Comment by w3con** [comment]
Fixed: [81daf7](https://github.com/Ecomi-Ecosystem/tge-contract/commit/81daf727bc584e3dce733e85dce29982e5dddb8c)
