### ISSUE TITLE
Any address could be used as Crowdsale or AllowanceProvider addresses 

### ISSUE THREAD

**Issue by w3con** [BlockchainLabsNZ/tge-contract-audit#7]
OMITokenLock.sol, [Line 69](https://github.com/BlockchainLabsNZ/tge-contract-audit/blob/2207b0d258c5dd4b35e3aaeca31077eb709d8d42/contracts/OMITokenLock.sol#L69):
```
function setCrowdsaleAddress (address _crowdsale)
    public
    onlyOwner
    returns (bool)
  {
    crowdsale = _crowdsale;
    return true;
  }
```
Consider to validate that crowdsale contract is an actual crowdsale contract, not just an address.

**Comment by w3con** [comment]
Unfortunately, casting to the contract address does not validate that the contract is the required contract. The best way to check it is to call one of the function of the contract and get the predicted return from it. It could be one of the existing functions of especially created one.  

For example:
```
require(_crowdsale.isRightContract());
```
and add the function `isRightContract() public pure returns(bool) { return true; }` to the crowdsale contract. 

Then you can be sure that the contract has at least one expected function. :)

**Comment by mikelduffy** [comment]
Fixed. I've added these correct contract validation functions to all of the contracts.

**Comment by w3con** [comment]
Fixed: [81daf7](https://github.com/Ecomi-Ecosystem/tge-contract/commit/81daf727bc584e3dce733e85dce29982e5dddb8c)
